#! /bin/bash
set -euo pipefail

installer_url=https://github.com/bazelbuild/bazel/releases/download/0.15.2/bazel-0.15.2-installer-linux-x86_64.sh
installer_sha256=13eae0f09565cf17fc1c9ce1053b9eac14c11e726a2215a79ebaf5bdbf435241

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
install_dir="${HOME}/.cache/bazel-install/${installer_sha256}"
bazel_real="${install_dir}/lib/bazel/bin/bazel-real"

if [[ ! -f "${bazel_real}" ]]; then
    function print_info() { printf "\033[0;32mINFO:\033[0m $*\n"; }
    print_info "Bazel installation not found, installing..."

    # Setup install directory
    mkdir -p "${install_dir}"

    # Delete .bazel on failure
    trap 'rm -rf "${install_dir}"' ERR INT TERM

    # Download bazel installer
    bazel_installer="${install_dir}/bazel-installer.sh"
    wget "${installer_url}" -O "${bazel_installer}"
    echo "${installer_sha256}  ${bazel_installer}" | sha256sum --check

    # Install bazel
    chmod +x "${bazel_installer}"
    "${bazel_installer}" --prefix="${install_dir}"
    rm -f "${bazel_installer}"
    print_info "Bazel installation complete."
fi

exec -a "$0" "${bazel_real}" "$@"
